ordo-one/package-benchmark

- Sources/BenchmarkSupport/BenchmarkRunner.swift
- Sources/Statistics/Statistics.swift
and other reversed polarity metrics.
Fixes https://github.com/ordo-one/package-benchmark/issues/10
> fix: Calculate all percentiles for throughput

- Documentation/GettingStarted.md
- Documentation/TODO.md
- Documentation/WritingBenchmarks.md
- Plugins/Benchmark/BenchmarkPlugin.swift
Fixes https://github.com/ordo-one/package-benchmark/issues/9
> fix: Make benchmark plugin discover tests in Benchmarks directory regardless of target name

- Sources/Benchmark/Benchmark.swift
Fixes https://github.com/ordo-one/package-benchmark/issues/24
Supports setting the thresholds for all tests in a suite like:
```swift
@_dynamicReplacement(for: registerBenchmarks)
func benchmarks() {
Benchmark.defaultTimeUnits = .microseconds
let customThreshold = BenchmarkResult.PercentileThresholds(relative: [.p50 : 5.0, .p75 : 10.0],
absolute: [.p25 : 10, .p50 : 15])
let customThreshold2 = BenchmarkResult.PercentileThresholds(relative: .strict)
let customThreshold3 = BenchmarkResult.PercentileThresholds(absolute: .relaxed)
Benchmark.defaultThresholds = [.wallClock : customThreshold,
.throughput : customThreshold2,
.cpuTotal: customThreshold3,
.cpuUser: .strict]
...
```
> feat: Support default thresholds for benchmark suite and rename defaultBenchmarkTimeUnits to defaultTimeUnits

- Documentation/TODO.md
- Sources/Benchmark/Benchmark.swift
- Sources/BenchmarkSupport/BenchmarkRunner+ReadWrite.swift
- Sources/BenchmarkSupport/MallocStats/MallocStatsProducer+jemalloc.swift
- Sources/BenchmarkSupport/NIOLock.swift
- Sources/BenchmarkSupport/OperatingSystemStats/OperatingSystemStatsProducer+Darwin.swift
- Sources/BenchmarkSupport/OperatingSystemStats/OperatingSystemStatsProducer+Linux.swift
Fixes https://github.com/ordo-one/package-benchmark/issues/21
Basically borrowed NIOLock for the time being until we have some other native swift concurrency primitive for synchronisation, using dispatch semaphores instead of pthread ones.
> chore: Move to dispatch conditions / NIOLock instead of raw pthread mutex/conditions

- Benchmarks/DateTime/DateTime.swift
- Package.resolved
- Package.swift
Moving DateTime benchmarks here to remove circular dependency.
Fixes sc-1033.
> fix: [sc-1033] Remove circular dependency on Benchmark

- Benchmarks/Histogram/HistogramBenchmark.swift
- Plugins/BenchmarkTool/BenchmarkTool+Operations.swift
- Plugins/BenchmarkTool/BenchmarkTool.swift
- Sources/Statistics/Statistics.swift
Run all benchmarks in isolated processes to get correct memory statistics, also some minor code cleanup (move to enum instead of strings for command, run swiftformat on all).
Fixes https://github.com/ordo-one/package-benchmark/issues/51
Performed basic manual testing.
> feat: Run all benchmarks in isolation

- Documentation/RunningBenchmarks.md
- Documentation/TODO.md
- Documentation/WritingBenchmarks.md
- Plugins/Benchmark/ArgumentExtractor+Extensions.swift
- Plugins/Benchmark/BenchmarkPlugin.swift
- Plugins/BenchmarkTool/BenchmarkTool+Operations.swift
- Plugins/BenchmarkTool/BenchmarkTool.swift
- Sources/Benchmark/Benchmark.swift
Rename skip -> skip-target, add regexp support to target/skip-targ, add filter/skip options with regexp support, multiple of each can be provided
Fixes https://github.com/ordo-one/package-benchmark/issues/58
This adds support for Regex for target/skip-target options, add new options for filter/skip that allow for regex filtering for what benchmarks should be run. 
Manual testing only
> feat: Add regex support for targets and benchmark for filter/skip

- Benchmarks/Basic/BenchmarkRunner.swift
- Benchmarks/DateTime/DateTime.swift
- Benchmarks/Histogram/HistogramBenchmark.swift
- Plugins/Benchmark/ArgumentExtractor+Extensions.swift
- Plugins/BenchmarkTool/BenchmarkTool+Operations.swift
- Sources/Benchmark/Benchmark.swift
- Sources/BenchmarkSupport/BenchmarkRunner.swift
- Tests/BenchmarkTests/BenchmarkRunnerTests.swift
- Tests/BenchmarkTests/BenchmarkTests.swift
Refactored configuration into a separate type and simplified the benchmark init signature accordingly.
This allows for sharing of configurations between benchmarks more easily, but is a source break.
It's trivial to change existing options for a benchmark though, e.g.
```swift
Benchmark("Memory transient allocations + 1 large leak",
metrics: BenchmarkMetric.memory,
throughputScalingFactor: .kilo) { benchmark in
performAllocations(count: benchmark.throughputScalingFactor.rawValue, size: 11 * 1024 * 1024)
performAllocations(count: 1, size: 32 * 1024 * 1024, shouldFree: false)
}
```
becomes
```swift
Benchmark("Memory transient allocations + 1 large leak",
configuration: .init(metrics: BenchmarkMetric.memory,
throughputScalingFactor: .kilo)) { benchmark in
performAllocations(count: …
```
> feat: Add Configuration type to allow sharing of common configurations between benchmarks

- Benchmarks/Basic/BenchmarkRunner.swift
- Sources/BenchmarkSupport/BenchmarkRunner.swift
> fix: Let maxDuration affect the true wall clock time, not the accumulated run time

- Benchmarks/Basic/BenchmarkRunner.swift
- Sources/BenchmarkSupport/BenchmarkRunner.swift
- desiredIterations => maxIterations
- desiredDuration => maxDuration
Resolving build breakage in Xcode
build in Xcode
`swift build`
I tried `swift test`, but while it's building - on macOS I'm getting `error: Exited with signal code 11`.
I started to try and add a .devContainers directory setup to run within Docker, but ran into some permissions errors just doing `swift package resolve`, so I suspect it's unrelated to these changes.
> fix: fixed up external references after rename

- Benchmarks/Basic/BenchmarkRunner.swift
- Benchmarks/DateTime/DateTime.swift
- Benchmarks/Histogram/HistogramBenchmark.swift
- Documentation/WritingBenchmarks.md
- Plugins/Benchmark/BenchmarkPlugin+Help.swift
- Plugins/Benchmark/BenchmarkPlugin.swift
- Plugins/BenchmarkHelpGenerator/BenchmarkHelpGenerator.swift
- Plugins/BenchmarkTool/BenchmarkTool+Baselines.swift
- Plugins/BenchmarkTool/BenchmarkTool+Export+InfluxCSVFormatter.swift
- Plugins/BenchmarkTool/BenchmarkTool+Export+JMHFormatter.swift
- Plugins/BenchmarkTool/BenchmarkTool+Export.swift
- Plugins/BenchmarkTool/BenchmarkTool+PrettyPrinting.swift
- Plugins/BenchmarkTool/BenchmarkTool.swift
- Sources/Benchmark/Benchmark.swift
- Sources/Benchmark/BenchmarkInternals.swift
- Sources/Benchmark/BenchmarkMetric+Defaults.swift
- Sources/Benchmark/BenchmarkMetric.swift
- Sources/Benchmark/BenchmarkResult+Defaults.swift
- Sources/Benchmark/BenchmarkResult.swift
- Sources/Benchmark/Blackhole.swift
- Sources/Benchmark/Documentation.docc/BenchmarkMetric.md
- Sources/BenchmarkSupport/BenchmarkRunner.swift
- Sources/Statistics/Statistics.swift
- Tests/BenchmarkTests/BenchmarkMetricsTests.swift
- Tests/BenchmarkTests/BenchmarkResultTests.swift
- Tests/BenchmarkTests/BenchmarkTests.swift
- Tests/BenchmarkTests/StatisticsTests.swift
Fixes #66 
Fixes #68 
Fixes #71
Adds regex filtering to debug runs, make CPU time units conform to user specified time unit also for cpu total/user/cpu times. Add `--scale` option to command line to get output scaled to per-subiteration values.
Manual testing plus a few unit tests.
> chore: Make CPU time units consistent and polish scaling factor usage, improve debugging

- .devcontainer/devcontainer.json
- I'm working from a mac, so this makes it a lot easier for me to open, build, and test the package within a container while working from Visual Studio Code. It's leveraging the swift:5.7 docker container provided by Swift.org, and I extended that setup with a "devContainer feature" that ensures that jemalloc is installed in the related container.
Please describe the tests that you ran to verify your changes. 
The way I verified this:
- open the folder of checked out package within VSCode
- "Reopen with Container"
- Open an additional terminal and run the following commands:
```
swift package resolve
swift build
swift test
swift package benchmark
```
Not the speediest thing …
> feat: adds devContainer support

- Sources/Benchmark/BenchmarkResult.swift
- Sources/Benchmark/Documentation.docc/BenchmarkScalingFactor.md
- Sources/Benchmark/Documentation.docc/Documentation.md
- added curation for Scaling Factor
- added source documentation in scaling factor enum
Visually reviewed in Xcode, published into [GH pages fork](https://heckj.github.io/package-benchmark/documentation/benchmark/):
- https://heckj.github.io/package-benchmark/documentation/benchmark/
- https://heckj.github.io/package-benchmark/documentation/benchmark/benchmarkscalingfactor
> fix: doc cleanup after refactor and reorg

- Plugins/BenchmarkTool/BenchmarkTool+Export.swift
- Plugins/BenchmarkTool/BenchmarkTool.swift
- Sources/Benchmark/BenchmarkMetric.swift
Fixes https://github.com/ordo-one/package-benchmark/issues/92
Also unifies file naming for exported data.
> fix: Tab separated value output was broken

- Plugins/BenchmarkCommandPlugin/BenchmarkCommandPlugin.swift
- Plugins/BenchmarkTool/BenchmarkTool.swift
Hotfix wrong option naming after restructuring.
> fix: Update parameter naming after refactor

- Package.swift
- Sources/Benchmark/Documentation.docc/GettingStarted.md
- Sources/Benchmark/MallocStats/MallocStatsProducer+jemalloc.swift
- Tests/BenchmarkTests/OperatingSystemAndMallocTests.swift
Some platforms doesn't have jemalloc available and it'd be nice to be able to use benchmark without the malloc counters there.
Fixes #15
and
Fixes #60  (sort of)
To run test suite on macOS without crash you can now use:
`BENCHMARK_DISABLE_JEMALLOC=1 swift test`
To run benchmarks without jemalloc installed:
`BENCHMARK_DISABLE_JEMALLOC=1 swift package benchmark`
Manually tested with jemalloc installed/uninstalled.
> feat: Make it possible to build and run without jemalloc available

- Benchmarks/DateTime/BenchmarkRunner+DateTime.swift
- Benchmarks/Histogram/BenchmarkRunner+Histogram.swift
- Package.resolved
- Package.swift
- Plugins/BenchmarkCommandPlugin/BenchmarkPlugin+Help.swift
- Plugins/BenchmarkHelpGenerator/BenchmarkHelpGenerator.swift
- Sources/Benchmark/ARCStats/ARCStats.swift
- Sources/Benchmark/ARCStats/ARCStatsProducer.swift
- Sources/Benchmark/BenchmarkExecutor+Extensions.swift
- Sources/Benchmark/BenchmarkExecutor.swift
- Sources/Benchmark/BenchmarkMetric+Defaults.swift
- Sources/Benchmark/BenchmarkMetric.swift
- Sources/Benchmark/BenchmarkResult.swift
- Sources/Benchmark/BenchmarkRunner.swift
- Sources/Benchmark/Documentation.docc/BenchmarkMetric.md
- Sources/Benchmark/Documentation.docc/Metrics.md
- Sources/Benchmark/Documentation.docc/RunningBenchmarks.md
- Sources/Benchmark/MallocStats/MallocStatsProducer+jemalloc.swift
- Sources/Benchmark/OperatingSystemStats/OperatingSystemStatsProducer+Darwin.swift
- Sources/Benchmark/Statistics.swift
- Sources/SwiftRuntimeHooks/include/SwiftRuntimeHooks.h
- Sources/SwiftRuntimeHooks/shims.c
- Tests/BenchmarkTests/BenchmarkMetricsTests.swift
- Tests/BenchmarkTests/OperatingSystemAndMallocTests.swift
Adds retains, releases and abs(retain-release) metrics based (thanks to @ser-0xff for the low level hooking).
Fixes #115 
and
Fixes #128
Sample output:
```bash
Releases
╒═══════════════════════════════════════════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╤═════════╕
│ Test                                          │      p0 │     p25 │     p50 │     p75 │     p90 │     p99 │    p100 │ Samples │
╞═══════════════════════════════════════════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╡
│ Basic:Scaled metrics                          │       8 │       8 │       8 │       8 │       8 │       8 │       8 │    7630 │
├───────────────────────────────────────────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼── …
```
> feat: Add metrics for ARC

- Benchmarks/Basic/BenchmarkRunner+Basic.swift
- Sources/Benchmark/ARCStats/ARCStatsProducer.swift
- Sources/Benchmark/Benchmark.swift
- Sources/Benchmark/BenchmarkExecutor.swift
- Sources/Benchmark/MallocStats/MallocStatsProducer+jemalloc.swift
More idiomatic Swift usage in benchmark run, in the measurement path for better ARC stats. Added some comments, Added one stats benchmark for ARC testing. Remove DocC comment that fails swift test run on toolchain 5.7.1.
Manual test and standard test suite.
> fix: Cleanup ARC stats 

- README.md
Small tweak to README to correct adding a plugin to a benchmark target as per the [spm docs](https://github.com/apple/swift-package-manager/blob/main/Documentation/Plugins.md#making-use-of-a-build-tool-plugin)
I've updated my own usage of package-benchmark to the correct `plugins: [...]` syntax and confirmed that benchmarks still work as expected
~~- [ ] I have added `DocC` code-level documentation for any public interfaces exported by the package~~ N/A
~~- [ ] I have added unit and/or integration tests that prove my fix is effective or that my feature works~~ N/A
> docs: Correct readme for adding benchmark targets manually

- Package.swift
- Plugins/BenchmarkTool/BenchmarkTool+CreateBenchmark.swift
- Sources/Benchmark/Benchmark.swift
- Sources/Benchmark/BenchmarkResult.swift
- Tests/BenchmarkTests/BenchmarkResultTests.swift
- Tests/BenchmarkTests/StatisticsTests.swift
Fix benchmark init generation to add proper dependencies (as mentioned in (https://github.com/ordo-one/package-benchmark/pull/157)) - fix the local benchmark targets too.
> fix(minor): Fix improper generation of benchmark targets

- Package.swift
- Platform/CDarwinOperatingSystemStats/include/CDarwinOperatingSystemStats.h
- Sources/Benchmark/Benchmark.swift
- Sources/Benchmark/OperatingSystemStats/OperatingSystemStatsProducer+Darwin.swift
Use `CDarwinOperatingSystemStats` on iOS but stub out all uses of `libproc.h`. Let `makeOperatingSystemStats()` return at least information about number of threads.
> chore(patch): [sc-2205] Stub out libproc.h on iOS

- Benchmarks/Basic/Basic+SetupTeardown.swift
- Benchmarks/Basic/BenchmarkRunner+Basic.swift
- Benchmarks/DateTime/DateTime.swift
- Benchmarks/Histogram/Histogram.swift
- Package.swift
- Plugins/BenchmarkTool/BenchmarkTool+CreateBenchmark.swift
- Plugins/BenchmarkTool/BenchmarkTool+Export.swift
- Plugins/BenchmarkTool/BenchmarkTool+Operations.swift
- Plugins/BenchmarkTool/BenchmarkTool.swift
- Sources/Benchmark/Benchmark.swift
- Sources/Benchmark/BenchmarkExecutor+Extensions.swift
- Sources/Benchmark/BenchmarkInternals.swift
- Sources/Benchmark/BenchmarkMetric+Defaults.swift
- Sources/Benchmark/BenchmarkResult.swift
- Sources/Benchmark/BenchmarkRunner.swift
- Sources/Benchmark/BenchmarkThresholds+Defaults.swift
- Sources/Benchmark/Blackhole.swift
- Sources/Benchmark/OperatingSystemStats/OperatingSystemStatsProducer+Darwin.swift
- Sources/Benchmark/OperatingSystemStats/OperatingSystemStatsProducer+Linux.swift
- Tests/BenchmarkTests/BenchmarkTests.swift
Improves ergonomics of benchmark metric selection to allow writing `.all` instead of `BenchmarkMetric.all`
Manual tests.
- [] I have added unit and/or integration tests that prove my fix is effective or that my feature works
> feat(minor): Improve metric api ergonomics (#175)

- Sources/Benchmark/OperatingSystemStats/OperatingSystemStatsProducer+Darwin.swift
- Tests/BenchmarkTests/OperatingSystemAndMallocTests.swift
Support 2 IO counters on macOS: physical bytes read and written as reported by `proc_pid_rusage()` --https://opensource.apple.com/source/xnu/xnu-7195.141.2/bsd/sys/resource.h.auto.html
https://opensource.apple.com/source/xnu/xnu-7195.141.2/libsyscall/wrappers/libproc/libproc.h.auto.html
> feat(patch): support some IO counters on macOS via proc_pid_rusage()

- Sources/Benchmark/Benchmark+ConvenienceInitializers.swift
- Sources/Benchmark/Benchmark.swift
- Sources/Benchmark/BenchmarkExecutor.swift
- Sources/Benchmark/BenchmarkRunner.swift
- Sources/Benchmark/Documentation.docc/WritingBenchmarks.md
- Sources/Benchmark/OperatingSystemStats/OperatingSystemStatsProducer+Darwin.swift
- Sources/Benchmark/OperatingSystemStats/OperatingSystemStatsProducer+Linux.swift
Deducts the syscall overhead for cleaner statistics.
Fix the broken API for setup closures.
> fix(minor): Fix incorrect syscalls

- Plugins/BenchmarkTool/BenchmarkTool+Export+InfluxCSVFormatter.swift
The datatype header should have 14 values to match the 14 column headers.
When working with the .csv file produced by `--format influx` flag, I noticed that a few datatype headers were misaligned with their corresponding columns, and the `time` column was missing a datatype header entirely. The list of datatype headers seems to be missing one instance of `tag`.
Actual behavior
|tag|tag|tag|tag|tag|tag|tag|tag|double|double|long|long|dateTime||
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|measurement|hostName|processoryType|processors|memory|kernelVersion|metric|unit|test|value|test_average|iterations|warmup_iterations|time|
Expected behavior
|tag|tag|tag|tag|tag|tag|tag|tag|tag|double|double|long|long|dateTime|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---| …
> fix: Add missing tag in Influx datatype header

- Sources/Benchmark/BenchmarkExecutor.swift
- Sources/Benchmark/BenchmarkMetric.swift
- Sources/Benchmark/MallocStats/MallocStatsProducer+jemalloc.swift
- Sources/Benchmark/OperatingSystemStats/OperatingSystemStatsProducer+Darwin.swift
- Sources/Benchmark/OperatingSystemStats/OperatingSystemStatsProducer+Linux.swift
As reported here: https://forums.swift.org/t/compiler-optimisations-for-functional-style-collection-algorithms/68291/12
the peak resident memory counter showed invalid results - this PR enables the missing sampling for these two peak counters  (virtual/resident) so it provides expected results.
Also cleaned up the jemalloc epoch-poking that had some unnecessary boilerplate.
Test suite + manual testing with the test suite from here:
https://github.com/wadetregaskis/Swift-Benchmarks - tested on both macOS and Linux.
> chore(minor): Fix sampling for virtual/resident memory peaks

- Package.swift
- Tests/BenchmarkTests/OperatingSystemAndMallocTests.swift
Decrease the required swift-system version from 1.2 to 1.1 to allow for more projects to adopt package-benchmark - we don't strictly require anything from 1.2.
Test suite.
> feat(minor): Lower required swift-system version to 1.1 to facilitate benchmark adoption for more users

- Plugins/BenchmarkCommandPlugin/BenchmarkCommandPlugin.swift
- Plugins/BenchmarkCommandPlugin/Command+Helpers.swift
- Plugins/BenchmarkHelpGenerator/Command+Helpers.swift
- Plugins/BenchmarkTool/BenchmarkTool+Operations.swift
- Plugins/BenchmarkTool/BenchmarkTool.swift
- Plugins/BenchmarkTool/Command+Helpers.swift
- Sources/Benchmark/Documentation.docc/GettingStarted.md
- Tests/BenchmarkTests/AdditionalTests.swift
- Thresholds/P90AbsoluteThresholdsBenchmark.P90Malloc.p90.json
We used to unconditionally build all benchmark targets regardless of operation.
Changed logic so that we for baseline read/list/check operations don't rebuild, as we will not execute the benchmark for such operations.
> feat(minor): Avoid rebuilds

- Plugins/BenchmarkCommandPlugin/BenchmarkCommandPlugin.swift
Currently a failed build would silently return 0, so CI would be unable to detect such errors.
This PR makes sure that the command plugin will throw errors on any invalid input or for failed builds.
> fix(minor): Make CI fail for invalid arguments or failed builds

- Plugins/BenchmarkTool/BenchmarkTool.swift
After the changes in https://github.com/ordo-one/package-benchmark/pull/166 we no longer fail the run of the rest of the benchmarks if a single one fails, which is reasonable during normal iterative work. This is not ok for CI baseline checks though, so this PR restores failures when `baseline check` is performed.
> feat(minor): Make CI fail with regression for crashes or other run failures

- Plugins/BenchmarkCommandPlugin/BenchmarkCommandPlugin.swift
- Plugins/BenchmarkCommandPlugin/Command+Helpers.swift
- Plugins/BenchmarkHelpGenerator/Command+Helpers.swift
- Plugins/BenchmarkTool/BenchmarkTool+Baselines.swift
- Plugins/BenchmarkTool/BenchmarkTool.swift
- Plugins/BenchmarkTool/Command+Helpers.swift
To ensure we don't "succeed" when the benchmark throws due to permissioning errors (e.g. networking without disabling sandbox)
Manually tested with distributed system.
> fix(minor): Fail CI also for update benchmark baseline updates that fails due to EPERM

- Plugins/BenchmarkCommandPlugin/BenchmarkCommandPlugin.swift
Build the BenchmarkTool in release mode manually so we can use the optimised version for (much) faster JSON processing and benchmark reporting - this is a workaround for https://github.com/apple/swift-package-manager/issues/7210
Manually tested with both package-benchmark and SwiftNIO benchmarks.
> feat(minor): Manually build benchmarktool as release config

- Plugins/BenchmarkTool/BenchmarkTool+Baselines.swift
- Plugins/BenchmarkTool/BenchmarkTool+Operations.swift
- Plugins/BenchmarkTool/BenchmarkTool+PrettyPrinting.swift
- Plugins/BenchmarkTool/BenchmarkTool+ReadP90AbsoluteThresholds.swift
- Sources/Benchmark/BenchmarkClock.swift
- Sources/Benchmark/BenchmarkMetric+Defaults.swift
- Sources/Benchmark/BenchmarkResult.swift
- Sources/Benchmark/Documentation.docc/Benchmark.md
- Sources/Benchmark/Documentation.docc/BenchmarkMetric.md
- Sources/Benchmark/Documentation.docc/Benchmark_Configuration.md
- Sources/Benchmark/Documentation.docc/Documentation.md
- Sources/Benchmark/Progress/Progress.swift
- Sources/Benchmark/Progress/ProgressElements.swift
- Sources/Benchmark/Progress/Utilities.swift
- Sources/Benchmark/Statistics.swift
- Tests/BenchmarkTests/AdditionalTests.swift
- Tests/BenchmarkTests/BenchmarkResultTests.swift
For benchmarks that are not completely stable (in e.g. syscall/malloc count) due to use of e.g. async or networking, it is desirable to also be able to specify some leeway for benchmarks even for the absolute checks from thresholds.
This fixes https://github.com/ordo-one/package-benchmark/issues/220
By default the behaviour for absolute thresholds checks are as previously (strict, zero improvements/regressions are allowed), but now it is possible to define both absolute and relative thresholds for the benchmarks (as documented at https://swiftpackageindex.com/ordo-one/package-benchmark/1.21.3/documentation/benchmark/writingbenchmarks) 
> feat(minor): Support thresholds for absolute checks

- Benchmarks/Benchmarks/Basic/BenchmarkRunner+Basic.swift
- Sources/Benchmark/Documentation.docc/WritingBenchmarks.md
- Tests/BenchmarkTests/BenchmarkResultTests.swift
Added another sample for how to run parametrised benchmarks
Fixes https://github.com/ordo-one/package-benchmark/issues/224
> docs(patch): Add example on how parameterization is done

- Sources/Benchmark/Documentation.docc/Metrics.md
noticed this while working on adding HTML anchors to the [terms list](https://forums.swift.org/t/glossary-of-terms/70138/8) on this package’s [Swiftinit documentation](https://swiftinit.org/docs/package-benchmark/benchmark/metrics#st:writeBytesLogical)
> docs(patch): correct typo 

- Plugins/BenchmarkCommandPlugin/BenchmarkCommandPlugin.swift
- Plugins/BenchmarkTool/BenchmarkTool.swift
Always surface failed job return codes up to CI, fixes #230.
> fix(patch): Always surface errors, fixes #230

- Sources/Benchmark/OperatingSystemStats/OperatingSystemStatsProducer+Linux.swift
When reading from the file descriptor into the temporary buffer, it was only by happenstance that the buffer would contain a terminating nul byte.
The buffer is uninitialized and thus may contain any data.
And the `/proc` files that are read into the buffer are **not** nul terminated.
If the temporary buffer happened to be zero-initialized, then this would accidentally work correctly.
If the temporary buffer happened to have a nul byte somewhere after the read data and in-bounds, then the end of the resulting String would be corrupted with arbitrary crud. This crud would ostensibly be after a terminating newline and thus parsers might have ignored it?
If the temporary buffer happened to not have any nul bytes after the read data, then other Bad Things could happen, including silent …
> fix(patch): memory unsafe file read on Linux

- Plugins/BenchmarkTool/BenchmarkTool+PrettyPrinting.swift
https://github.com/ordo-one/package-benchmark/issues/245
A small change to support github markdown style tables.
Tested locally from `package-benchmark-samples`:
```
swift package benchmark --format markdown
```
Output looks correct. Tables are formatted in native GitHub table style:
https://gist.github.com/vanvoorden/466dae6b853e48e1b17f0966c6e29c43
We can test the default table style:
```
swift package benchmark --format text
```
Output looks unchanged:
https://gist.github.com/vanvoorden/234170b07f19e4aa59fb9944fbfdfb31
> fix: support github markdown table style

- Sources/Benchmark/BenchmarkExecutor.swift
> fix(patch): Tighten the scope between wallclock and cpu total

- Package.swift
- Sources/Benchmark/OperatingSystemStats/OperatingSystemStatsProducer+Darwin.swift
`proc_taskinfo()` and friends are not available on iOS.
> chore(patch): [sc-10781] No procinfo on mobile platforms - stub out + disable jemalloc

- Benchmarks/Benchmarks/Basic/BenchmarkRunner+Basic.swift
- Sources/Benchmark/Benchmark.swift
- Sources/Benchmark/BenchmarkExecutor.swift
Adding support for per-iteration signposts as requested in 
https://github.com/ordo-one/package-benchmark/issues/259
Manually verified.
> feat(minor): Add signposts for explicit starts

- Plugins/BenchmarkCommandPlugin/BenchmarkCommandPlugin.swift
- Plugins/BenchmarkCommandPlugin/BenchmarkPlugin+Help.swift
- Plugins/BenchmarkHelpGenerator/BenchmarkHelpGenerator.swift
- Sources/Benchmark/Documentation.docc/RunningBenchmarks.md
Fixes https://github.com/ordo-one/package-benchmark/issues/246
Usage:
```
swift package benchmark --Xswiftc lto=llvm-full --Xswiftc experimental-hermetic-seal-at-link
```
Manual testing with debug output to verify that appropriate options are passed to swiftc.
> feat(minor): Support swiftc option passthrough

- Plugins/BenchmarkTool/BenchmarkTool+Operations.swift
Suppress some logs in `thresholds` subcommand when using `--no-progress`:
<kbd> <img width="934" alt="Screenshot 2024-10-04 at 10 52 55 PM" src="https://github.com/user-attachments/assets/4254fb63-77d0-4b0b-a0ce-29c8198c4e0d"> </kbd>
> fix(patch): Log less when `--no-progress` in `thresholds` subcommand

- Plugins/BenchmarkTool/BenchmarkTool+Operations.swift
The last PR made it so it requires the `--quiet` flag to silence those logs.
This wasn't my intention, I wanted `--no-progress` to do that.
Using `--quiet` will make the benchmark comparison not report what regressed if anything has regressed, so I don't want to use that flag.
<This time actually tested the PR against our repo>
> fix(patch): Log less when `--no-progress` (again)

- .spi.yml
> chore: Update .spi.yml

- README.md
Updates readme to fix the broken benchmark example, fixes #295 which contains more information.
Tested running the benchmark from an empty project.
> docs: Update readme to fix broken example benchmark

- .github/workflows/swift-macos-previous.yml
- Benchmarks/Benchmarks/Basic/Basic+SetupTeardown.swift
- Benchmarks/Benchmarks/Basic/BenchmarkRunner+Basic.swift
- Benchmarks/Benchmarks/DateTime/DateTime.swift
- Benchmarks/Benchmarks/Histogram/Histogram.swift
- Benchmarks/Benchmarks/P90AbsoluteThresholds/P90AbsoluteThresholds.swift
- Benchmarks/Package.swift
- Package.swift
- Plugins/BenchmarkCommandPlugin/Command+Helpers.swift
- README.md
- Sources/Benchmark/ARCStats/ARCStats.swift
- Sources/Benchmark/Benchmark+ConvenienceInitializers.swift
- Sources/Benchmark/Benchmark.swift
- Sources/Benchmark/BenchmarkClock.swift
- Sources/Benchmark/BenchmarkInternals.swift
- Sources/Benchmark/BenchmarkMetric.swift
- Sources/Benchmark/BenchmarkResult.swift
- Sources/Benchmark/BenchmarkRunner.swift
- Sources/Benchmark/Documentation.docc/BenchmarkTimeUnits.md
- Sources/Benchmark/Documentation.docc/BenchmarkUnits.md
- Sources/Benchmark/Documentation.docc/Benchmark_Configuration.md
- Sources/Benchmark/MallocStats/MallocStats.swift
- Sources/Benchmark/MallocStats/MallocStatsProducer+jemalloc.swift
- Sources/Benchmark/Progress/Progress.swift
- Sources/Benchmark/Progress/ProgressElements.swift
- Sources/Benchmark/Progress/Utilities.swift
- Sources/Benchmark/Statistics.swift
- Sources/Shared/Command+Helpers.swift
Add property wrapper to reduce boilerplate
Fixes https://github.com/ordo-one/package-benchmark/issues/311
Tested with benchmark samples and included benchmarks.
> fix(minor): Make setup/teardown hooks Swift 6 usable

- Sources/Benchmark/Benchmark.swift
- Sources/Benchmark/BenchmarkRunner.swift
- Sources/Benchmark/OutputSuppressor.swift
When running with --no-progress, we reroute stdout/stderr to /dev/null for the benchmark.
Addresses https://github.com/ordo-one/package-benchmark/issues/288
> feat(patch): Add output suppressor when running with --no-progress

- Plugins/BenchmarkTool/BenchmarkTool+Export+InfluxCSVFormatter.swift
This PR adds a percentile column for the influx export format using the default percentile values. This would close #227. 
Example output of `swift package --allow-writing-to-package-directory benchmark --format influx`
```
#datatype tag,tag,tag,tag,tag,tag,tag,tag,tag,double,double,double,long,long,dateTime
measurement,hostName,processoryType,processors,memory,kernelVersion,metric,unit,test,percentile,value,test_average,iterations,warmup_iterations,time
LanguageCoverage,ckumar,arm64,14,36,Darwin-Kernel-Version-23.6.0:-Fri-Nov-15-15:12:52-PST-2024;-root:xnu-10063.141.1.702.7~1/RELEASE_ARM64_T6031,ratio,K,eight operations looped,0.0,47950,61914.57142857143,17,1,2025-03-14T12:02:23Z
LanguageCoverage,ckumar,arm64,14,36,Darwin-Kernel-Version-23.6.0:-Fri-Nov-15-15:12:52-PST-2024;-root:xnu-10063 …
```
> feat: add percentile column to influx format

- Sources/Benchmark/BenchmarkResult.swift
Actually resolves #277. EDIT: or actually not sure if this solves the same issue. But solves an issue anyway.
Examples:
Incorrect label, saying "M" aka "Mega" (or I guess "Millions" also reads fine):
<kbd> <img width="832" height="214" alt="Incorrect unit label M denoting Mega" src="https://github.com/user-attachments/assets/f8e7419f-994d-4893-a9c3-72954a4c78ce" /> </kbd>
Correct label, saying "K" aka "Kilo":
<kbd> <img width="822" height="191" alt="Correct unit label K denoting Kilo" src="https://github.com/user-attachments/assets/e1953acc-4489-4b24-a7e1-7a84a97e0bb2" /> </kbd>
To be completely clear, both these images are 100% correct other than the first image mentioning "M" aka 10^6.
Feel free to review on your own schedule.
Manually in my PRs.
> fix: Fix occasionally incorrect unit in some tables [2/4]
