ordo-one/package-benchmark

Sources/Statistics/Statistics.swift

.cpuSystem on Linux would often yield 0 as granularity was 10ms and as first sample was zero, we'd go for nanos as scale.
Now we'll wait until the first non-zero sample to deduce which auto scale to use (and fall back to .count if we only get zero samples in the whole run).

fix: Better support automatic scaling for initial zero samples

---

Sources/Benchmark/Benchmark.swift

This fixes https://github.com/ordo-one/package-benchmark/issues/5

feat: Add convenience range computed property for nicer inner loop iterators

---

Documentation/WritingBenchmarks.md
Sources/Benchmark/Benchmark.swift
Sources/BenchmarkSupport/BenchmarkRunner.swift
Tests/BenchmarkTests/BenchmarkRunnerTests.swift
Tests/BenchmarkTests/BenchmarkTests.swift

Fixes https://github.com/ordo-one/package-benchmark/issues/26 and https://github.com/ordo-one/package-benchmark/issues/27

feat: Adding ability to set defaults for all benchmark settings for a suite and move warmup->warmupIterations

---

Plugins/BenchmarkTool/BenchmarkTool+Baselines.swift
Sources/Benchmark/BenchmarkResult+Defaults.swift
Sources/Benchmark/BenchmarkResult.swift
Tests/BenchmarkTests/BenchmarkResultTests.swift
Tests/BenchmarkTests/BenchmarkRunnerTests.swift

Fixes https://github.com/ordo-one/package-benchmark/issues/31

fix: Fix comparisons of absolute thresholds, add helpers for defining them

---

.spi.yml
Package.resolved
Package.swift

Try adding support for SPI + DocC - first step.

feat: SwiftPackageIndex support

---

Sources/Benchmark/BenchmarkInternals.swift
Sources/BenchmarkSupport/MallocStats/MallocStats+jemalloc-support.swift
Sources/Statistics/Statistics.swift

ci: restore swiftlint

---

Sources/BenchmarkSupport/MallocStats/MallocStatsProducer+jemalloc.swift

chore: Cleanup jemalloc helper

---

Sources/.swiftlint.yml
Sources/BenchmarkSupport/MallocStats/MallocStatsProducer+jemalloc.swift

chore: Fix SwiftLint warnings

---

Benchmarks/Histogram/HistogramBenchmark.swift
Package.resolved
Package.swift
Sources/Statistics/Statistics.swift
Tests/BenchmarkTests/BenchmarkResultTests.swift
Tests/BenchmarkTests/BenchmarkRunnerTests.swift
Tests/BenchmarkTests/BenchmarkTests.swift
Tests/BenchmarkTests/OperatingSystemAndMallocTests.swift
Tests/BenchmarkTests/StatisticsTests.swift

This fixes https://github.com/ordo-one/package-benchmark/issues/40

feat: Integrate with hdr histogram

---

Benchmarks/Histogram/HistogramBenchmark.swift
Tests/BenchmarkTests/OperatingSystemAndMallocTests.swift
Tests/BenchmarkTests/StatisticsTests.swift

fix: correct histogram benchmark

---

Benchmarks/Basic/BenchmarkRunner.swift
Benchmarks/DateTime/DateTime.swift
Benchmarks/Histogram/HistogramBenchmark.swift
Documentation/Workflows.md
Documentation/WritingBenchmarks.md
README.md
Sources/Benchmark/Benchmark.swift
Sources/BenchmarkSupport/BenchmarkRunner.swift
Tests/BenchmarkTests/BenchmarkRunnerTests.swift

This fixes #65, it makes the point of use for these settings clearer.

chore: Change naming of desiredIterations/desiredDuration -> maxIterations/maxDuration

---

.devcontainer/devcontainer.json

migrated `jemalloc` feature in previous devContainer into a different repo to coordinate my "features" work
- opened `Package.swift` within VSCode
- `Reopen within Container`
- `new terminal in container`
- `swift package resolve`
- `swift build`
- `swift test`

chore: migrated jemalloc feature to a broader set

---

Sources/Benchmark/Documentation.docc/ComparingBenchmarksCI.md
Sources/Benchmark/Documentation.docc/CreatingAndComparingBaselines.md
Sources/Benchmark/Documentation.docc/Documentation.md
Sources/Benchmark/Documentation.docc/ExportingBenchmarks.md
Sources/Benchmark/Documentation.docc/GettingStarted.md
Sources/Benchmark/Documentation.docc/Metrics.md
Sources/Benchmark/Documentation.docc/RunningBenchmarks.md
Sources/Benchmark/Documentation.docc/WritingBenchmarks.md

Corrected and improved documentation.
Tested with Xcode build documentation.

chore: Improve documentation

---

Plugins/Benchmark/BenchmarkPlugin.swift
Plugins/Benchmark/Command+Helpers.swift
Plugins/BenchmarkTool/BenchmarkTool+Baselines.swift
Plugins/BenchmarkTool/BenchmarkTool+Export.swift
Plugins/BenchmarkTool/BenchmarkTool+Operations.swift
Plugins/BenchmarkTool/BenchmarkTool+PrettyPrinting.swift
Plugins/BenchmarkTool/BenchmarkTool.swift
Plugins/BenchmarkTool/Command+Helpers.swift
Plugins/BenchmarkTool/String+Additions.swift
Sources/Benchmark/BenchmarkResult.swift
Sources/BenchmarkSupport/BenchmarkExecutor.swift
Sources/BenchmarkSupport/BenchmarkRunner.swift

fix: Clean up required baseline parameters for consistency, cleanup of parameter passing to child process

---

Benchmarks/Basic/BenchmarkRunner+Basic.swift
Plugins/Benchmark/BenchmarkPlugin.swift
Plugins/BenchmarkTool/BenchmarkTool+Operations.swift
Plugins/BenchmarkTool/BenchmarkTool+PrettyPrinting.swift
Plugins/BenchmarkTool/BenchmarkTool.swift
Sources/Benchmark/BenchmarkMetric.swift
Sources/BenchmarkSupport/BenchmarkExecutor.swift
Sources/BenchmarkSupport/BenchmarkRunner.swift
Tests/BenchmarkTests/BenchmarkMetricsTests.swift

feat: Display test names properly with metric grouping, add support for on-the-fly specification of metrics.

---

Plugins/BenchmarkTool/BenchmarkTool+Export.swift

Fixes https://github.com/ordo-one/package-benchmark/issues/90

feat: histogram percentile export fixes

---

Plugins/BenchmarkTool/BenchmarkTool+Operations.swift
Plugins/BenchmarkTool/BenchmarkTool+PrettyPrinting.swift
Plugins/BenchmarkTool/BenchmarkTool.swift

Use proper typing for bools
Fixes  #114

chore: Move to booleans instead of ints, fixes #114

---

Sources/BenchmarkSupport/BenchmarkResult.swift
Tests/BenchmarkTests/BenchmarkResultTests.swift

Fix incorrect scaling of delta absolute comparisons, add one more unit test.

fix: Fix absolute comparisons

---

Plugins/BenchmarkTool/BenchmarkTool+Operations.swift
Sources/Benchmark/Benchmark.swift
Sources/Benchmark/BenchmarkRunner.swift

chore: make startup and shutdown hooks async (and throwing)

---

Package.swift

Incorrect boolean check fixed.

fix: Update Package.swift

---

Sources/Benchmark/OperatingSystemStats/OperatingSystemStatsProducer+Darwin.swift
Sources/Benchmark/OperatingSystemStats/OperatingSystemStatsProducer+Linux.swift

Workaround https://github.com/apple/swift/issues/60876 so we can build with Swift 5.7 again

fix: Fix Swift 5.7 toolchain support

---

Package.resolved
Package.swift

fix: Make SPI builds work for macOS

---

Sources/Benchmark/Documentation.docc/WritingBenchmarks.md

chore: correct scalingFactor type in documentation

---

Plugins/BenchmarkTool/BenchmarkTool+CreateBenchmark.swift

fix(patch): Update BenchmarkTool+CreateBenchmark.swift

---

Package.resolved
Package.swift
Platform/CDarwinOperatingSystemStats/include/CDarwinOperatingSystemStats.h

Updated an `#ifdef` to not use `Jemalloc` on iOS.

chore(patch): [sc-2205] Update to datetime 1.0.1, add iOS target

---

Sources/Benchmark/BenchmarkResult.swift

fix(patch): Show exact deviations if rounded are zero

---

Sources/Benchmark/Documentation.docc/RunningBenchmarks.md

Add documentation on how to work around the jemalloc Xcode problem.

chore(patch): Update RunningBenchmarks.md

---

README.md

Removes an outdated section in the README.

docs: Remove outdated section

---

Plugins/BenchmarkTool/BenchmarkTool+Export+InfluxCSVFormatter.swift
Plugins/BenchmarkTool/BenchmarkTool+Operations.swift
Plugins/BenchmarkTool/BenchmarkTool+PrettyPrinting.swift
Plugins/BenchmarkTool/BenchmarkTool+ReadP90AbsoluteThresholds.swift
Sources/Benchmark/Benchmark+ConvenienceInitializers.swift
Sources/Benchmark/BenchmarkExecutor.swift
Sources/Benchmark/BenchmarkMetric+Defaults.swift
Sources/Benchmark/BenchmarkMetric.swift
Sources/Benchmark/BenchmarkResult.swift

Optimize a bit for better support for cpu-only micro benchmarks.
Manual testing, test suite.

feat(minor): Performance optimization and a few bug fixes

---

Sources/Benchmark/Benchmark.swift
Sources/Benchmark/Documentation.docc/WritingBenchmarks.md

I fixed typos in the documentation and the comment.
I checked them on GitHub's markdown preview.

fix(patch): Fix typos

---

Sources/Benchmark/NIOConcurrencyHelpers/lock.swift

Make the SwiftNIO borrowed `Lock` non-public, should definitely not be exported.

fix(patch): Fix incorrect public export of Lock

---

Plugins/BenchmarkTool/BenchmarkTool.swift

fix(patch): Reenable benchmark init

---

Platform/CLinuxOperatingSystemStats/CLinuxOperatingSystemStats.c

fix(patch): Fix build on old Linux versions

---

Package.swift
Sources/Benchmark/BenchmarkClock.swift
Sources/Benchmark/OperatingSystemStats/OperatingSystemStatsProducer+Darwin.swift

feat(patch): At least fix ifdefs for additional platforms

---

Package.swift
Sources/Benchmark/BenchmarkClock.swift
Sources/Benchmark/OperatingSystemStats/OperatingSystemStatsProducer+Darwin.swift

Fix https://github.com/ordo-one/package-benchmark/issues/256

fix(patch): Fix issues with broken build when visionOS is unknown

---

.github/workflows/swift-sanitizer-address.yml

fix: Update swift-sanitizer-address.yml

---

README.md

chore: Update README.md with CI status badges for builds

---

.github/workflows/swift-macos-previous.yml

ci: disable tmate debug
